package com.fida.fida_backend.entity.user;

public enum ExpensesType {
    BESLENME_VE_GIDA,
    BARINMA_VE_EV_GIDERLERI,
    FATURALAR_VE_ABONELIKLER,
    ULASIM_VE_ARAC,
    SAGLIK_VE_KISISEL_BAKIM,
    EGLENCE_VE_SOSYALLESME,
    EGITIM_VE_GELISIM,
    GIYIM_VE_AKSESUAR,
    YATIRIM_VE_TASARRUF,
    BORC_VE_TAKSIT_ODEMELERI,
    HEDIYE_VE_BAGIS,
    COCUK_VE_EVCIL_HAYVAN,
    VERGI_VE_SIGORTA,
    DIGER
}
